services:
  - type: web
    name: restore-v2
    runtime: dotnet
    repo: https://github.com/MahmoudSamir2003/Restore-v2.git
    branch: master
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/Api.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
