services:
  - type: web
    name: restore-v2
    env: docker
    repo: https://github.com/MahmoudSamir2003/Restore-v2.git
    branch: master
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "YourConnectionStringHere"
